$:
  vscode:
    - docker:
        build: .ide/Dockerfile
        by:
          - .ide/setting.json
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
