$:
  vscode:
    - docker:
        image:
          name: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
          dockerUser: $CNB_TOKEN_USER_NAME
          dockerPassword: $CNB_TOKEN
        volumes:
          - ./backend/.venv:read-write
          - ./frontend/node_modules:read-write
      services:
        - vscode
        - docker
      imports:
        - https://cnb.cool/shiyezzz/material/-/blob/main/mysql.yml
      stages:
        - name: ls
          script: ls -al

  push:
    - stages:
        - name: sync to github
          imports: https://cnb.cool/pylover/key/-/blob/main/github.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/pylover7/MaterialManager.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

  pull_request:
    - stages:
      - name: 代码评审
        image: cnbcool/ai-review:latest
        settings:
          type: code-review
# .cnb.yml
"**":  # 触发的分支名，默认所有分支，按需修改
  push:  # push触发，也可以用merge_request等触发
  - stages:
    # 代码分析
    - name: TCA
      image: tencentcom/tca-plugin:latest
      settings:
        org_sid: DlV3t9YzRYP  # 团队编号，从TCA官网获取
        team_name: material  # 项目名称，从TCA官网获取
        scheme_id: 7529  # 分析方案id，从TCA官网获取
      settingsFrom:
        # 密钥文件引用。请检查使用此配置的代码库是否具有访问密钥文件的权限，否则会导致构建失败！
        - https://cnb.cool/pylover/key/-/blob/main/tca.yml
