$:
  vscode:
    - docker:
        build:
          dockerfile: .ide/Dockerfile
          by:
            - .ide/settings.json
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
