$:
  vscode:
    - docker:
        image:
          name: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
          dockerUser: $CNB_TOKEN_USER_NAME
          dockerPassword: $CNB_TOKEN
        volumes:
          - ./backend/.venv:read-write
          - ./frontend/node_modules:read-write
      services:
        - vscode
        - docker
      imports:
        - https://cnb.cool/shiyezzz/material/-/blob/main/mysql.yml
      stages:
        - name: ls
          script: ls -al

  push:
    - stages:
        - imports: https://cnb.cool/pylover/key/-/blob/main/github.yml
          name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/pylover7/MaterialManager.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
      # 代码分析
        - name: Backend TCA
          image: tencentcom/tca-plugin:latest
          settings:
            block: false
            scan_dir: backend/app
        - name: Frontend TCA
          image: tencentcom/tca-plugin:latest
          settings:
            block: false
            scan_dir: frontend/src
  
  pull_request:
    - stages:
      - name: 代码评审
        image: cnbcool/ai-review:latest
        settings:
          type: code-review
