$:
  vscode:
    - docker:
        build:
          dockerfile: .ide/Dockerfile
          by:
            - .ide/settings.json
        volumes:
          - ./backend/.venv:read-write
          - ./frontend/node_modules:read-write
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
